controller_manager:
    ros__parameters:
        update_rate: 30
        use_sim_time: true

        jsc:
            type: "joint_state_controller/JointStateController"

        jmc:
            type: "velocity_controllers/JointGroupVelocityController"

jsc:
    ros__parameters:
        publish_rate: 50

jmc:
    ros__parameters:
        joints: 
            - joint_front_right_prop
            - joint_front_left_prop
            - joint_back_left_prop
            - joint_back_right_prop
        gains:
            joint_front_right_prop: {p: 10000, i: 1, d: 1000}
            joint_front_left_prop: {p: 10000, i: 1, d: 1000}
            joint_back_left_prop: {p: 10000, i: 1, d: 1000}
            joint_back_right_prop: {p: 10000, i: 1, d: 1000}